/**
 * Events.
 */
enum Event {
  ApprovedAutomodMessage = 'approvedautomodmessage',
  AutomodMessageApproved = 'automodmessageapproved',
  AutomodMessageDenied = 'automodmessagedenied',
  AutomodMessageRejected = 'automodmessagerejected',
  Ban = 'ban',
  Cheer = 'cheer',
  Clearchat = 'clearchat',
  Connected = 'connected',
  Connecting = 'connecting',
  DeniedAutomodMessage = 'deniedautomodmessage',
  Disconnected = 'disconnected',
  EmoteOnly = 'emoteonly',
  EmoteSets = 'emotesets',
  FollowersOnly = 'followersonly',
  Hosted = 'hosted',
  Hosting = 'hosting',
  Logon = 'logon',
  Message = 'message',
  MessageDeleted = 'messagedeleted',
  Mod = 'mod',
  Mods = 'mods',
  Notice = 'notice',
  Notices = 'notices',
  R9k = 'r9kbeta',
  Raid = 'raid',
  Reconnect = 'reconnect',
  ReSub = 'resub',
  Ritual = 'ritual',
  Roomstate = 'roomstate',
  Slowmode = 'slowmode',
  SubGift = 'subgift',
  Subscribers = 'subscribers',
  Subscription = 'subscription',
  Timeout = 'timeout',
  Unban = 'unban',
  Unhost = 'unhost',
  Unmod = 'unmod',
  Untimeout = 'untimeout',
  UserNotices = 'usernotices',
}

export default Event
