name: integration

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: '16'

      - name: Install dependencies
        run: yarn

      - name: Lint code
        run: yarn run lint
